### ISSUE TITLE
STM32H7 USB Support

### ISSUE THREAD

**Issue by mattico** [embassy-rs/embassy#1097]
Embassy is missing USB support for STM32H7 chips. I investigated what is different about them, though I haven't figured out how to fix the PAC yet. I probably won't have time to work on this for a long time, so I wanted to write down what I found.

## Peripheral Versions (from cubedb)
 - `otgfs1_v2_0`, same as `F4{6,7}9*` and `F7*`
 - `otgfs1_v2_4`, same as `L4A*` and `L496`

Fix: Add to perimap.

## Register Blocks

Some H7 chips have multiple USB controllers, so all the register blocks have a number .e.g. `USB1_HS_DEVICE`.

Fix: I think this is already handled somewhere.

## RCC

The H7 RCC fields for USB are named differently. e.g. it has `USB1OTGEN` rather than `USB_OTG_HSEN` in registers/yaml. No separate clocks for HS/FS?

Fix: Not sure.

## Extracted YAML Diffs

Old USB peripherals have wrong description for "endpoint transfer size register", but H7 is correct. e.g. in f215.yaml endpoint 0 is described as endpoint-1.

H7 is missing the device each in/out endpoint interrupt registers, e.g. `DIEPEACHMSK1`, `DOEPEACHMSK1`.

H7 has some overlapping registers?

```yaml
    - name: DIEPCTL5
      description: OTG device endpoint-5 control register
      byte_offset: 416
      fieldset: DIEPCTL5
    - name: DIEPTSIZ6
      description: OTG_HS device endpoint transfer size register
      byte_offset: 416
      fieldset: DIEPTSIZ6
    - name: DTXFSTS6
      description: OTG_HS device IN endpoint transmit FIFO status register
      byte_offset: 420
      fieldset: DTXFSTS6
    - name: DIEPINT5
      description: OTG device endpoint-5 interrupt register
      byte_offset: 424
      fieldset: DIEPINT5
    - name: DIEPTSIZ7
      description: OTG_HS device endpoint transfer size register
      byte_offset: 424
      fieldset: DIEPTSIZ7

```
