### ISSUE TITLE
Problem when trying to connect with tcp socket on rarspberry pico w

### ISSUE THREAD

**Issue by teovillanueva** [embassy-rs/embassy#1543]
Hello! First time opening an issue here. Im new to embedded systems and rust. Im trying to open a connection and im getting this error `ERROR panicked at 'adding a socket to a full SocketSet'`. Apparently this error comes from the `smoltcp` crate. I've been trying to debug this but I just cant figure it out. This is what Im doing:

```rs
let mut rx_buffer = [0; 4096];
let mut tx_buffer = [0; 4096];

let mut socket = TcpSocket::new(stack, &mut rx_buffer, &mut tx_buffer);

socket.set_timeout(Some(Duration::from_secs(10)));

let host_addr = embassy_net::Ipv4Address::from_str("192.168.1.3").unwrap();

if let Err(e) = socket.connect((host_addr, 1883)).await {
    warn!("connect error: {:?}", e);
}
```

EDIT:

This is my `Cargo.toml`

```toml
[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[features]
default = ["nightly"]
nightly = ["embassy-executor/nightly", "embassy-net/nightly", "embassy-time/nightly", "embassy-time/unstable-traits", "static_cell/nightly", "embedded-io/async", "embassy-net/nightly"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
defmt = "0.3"
defmt-rtt = "0.3"
fixed = "1.23.1"
fixed-macro = "1.2"
panic-probe = { version = "0.3", features = ["print-defmt"] }
embassy-executor = { version = "0.2.0", git = "https://github.com/embassy-rs/embassy", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-net = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["defmt", "nightly", "tcp", "udp", "dns", "dhcpv4", "medium-ethernet", "unstable-traits", "igmp"] }
embassy-rp = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["defmt", "unstable-traits", "nightly", "unstable-pac", "time-driver"] }
embassy-time = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = ["nightly", "defmt", "defmt-timestamp-uptime"] }
embassy-futures = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy" }
embassy-net-driver-channel = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy" }
reqwless = { version = "0.5.0", features = ["defmt"] }
cyw43 = { git = "https://github.com/embassy-rs/embassy", features = ["defmt", "firmware-logs"] }
cyw43-pio = {  git = "https://github.com/embassy-rs/embassy", features = ["defmt", "overclock"] }
embedded-hal-async = "0.2.0-alpha.1"
embedded-io = { version = "0.4.0", features = ["async", "defmt" ] }
embedded-nal = "0.6.0"
embedded-nal-async = "0.4.0"
futures = { version = "0.3.17", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
static_cell = { version = "1.1", features = ["nightly"]}
rand_core = "0.6.3"
serde-json-core = "0.5.0"
serde = { version = "1", default-features = false, features = ["derive"] }
rp-pac = "4.0.0"
shared = { path = "../shared" }
heapless = "0.7.15"
embedded-time = "0.12.1"
rust-mqtt = { version = "0.1.5", default-features = false }
smoltcp = { version = "0.9.0", default-features = false, features = [
  "proto-ipv4",
  "socket",
  "async",
]}
```
