### ISSUE TITLE
Not able to get ip address with esp32-s3 and embassy-net-wiznet

### ISSUE THREAD

**Issue by akesser** [embassy-rs/embassy#3210]
Hello altogether,

I tried to connect a esp32s3 (unexpected maker ProS3) to the ethernet via a wizen W5500 (Adafruit Ethernet FeatherWing), but I am not able to get an ip address.

This is the shortened version of my code:

```rust
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]

use embassy_embedded_hal::shared_bus::asynch::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_net::{Stack, StackResources};
use embassy_net_wiznet::chip::W5500;
use embassy_net_wiznet::{Device, Runner, State};
use embassy_sync::channel::{Channel, Receiver, Sender};
use embassy_sync::{blocking_mutex::raw::CriticalSectionRawMutex, mutex::Mutex};
use embassy_time::{Delay, Duration, Timer};
use embedded_hal_async::i2c::I2c;
use embedded_hal_bus::spi::ExclusiveDevice;
use esp_backtrace as _;
use esp_hal::gpio::{self, GpioPin, Level, Output};
use esp_hal::peripherals::SPI2;
use esp_hal::spi::master::dma::SpiDma;
use esp_hal::spi::FullDuplexMode;
use esp_hal::{
    clock::ClockControl,
    dma::*,
    dma_descriptors,
    gpio::Io,
    gpio::{AnyInput, Input, Pull},
    i2c::I2C,
    peripherals::{Peripherals, I2C0},
    prelude::*,
    spi::{
        master::{prelude::*, Spi},
        SpiMode,
    },
    system::SystemControl,
    timer::timg::TimerGroup,
    Async,
};
use static_cell::make_static;
use static_cell::StaticCell;

#[main]
async fn main(spawner: Spawner) {
    esp_println::logger::init_logger_from_env();

    log::info!("starting");

    let peripherals = Peripherals::take();

    let system = SystemControl::new(peripherals.SYSTEM);
    let clocks = ClockControl::max(system.clock_control).freeze();

    let timg0 = TimerGroup::new_async(peripherals.TIMG0, &clocks);

    esp_hal_embassy::init(&clocks, timg0);

    let io = Io::new(peripherals.GPIO, peripherals.IO_MUX);

    let sclk = io.pins.gpio36;
    let miso = io.pins.gpio37;
    let mosi = io.pins.gpio35;
    let cs = io.pins.gpio1;

    let dma = Dma::new(peripherals.DMA);

    let dma_channel = dma.channel0;

    let (descriptors, rx_descriptors) = dma_descriptors!(32000);

    let descriptors = make_static!(descriptors);
    let rx_descriptors = make_static!(rx_descriptors);
    let spi = Spi::new(peripherals.SPI2, 100.kHz(), SpiMode::Mode0, &clocks)
        .with_pins(Some(sclk), Some(mosi), Some(miso), None::<gpio::NoPinType>)
        .with_dma(dma_channel.configure_for_async(
            false,
            descriptors,
            rx_descriptors,
            DmaPriority::Priority0,
        ));

    let w5500_int = Input::new(io.pins.gpio3, Pull::Up); //io.pins.gpio16.into_pull_up_input();
    let w5500_reset = Output::new(io.pins.gpio2, Level::High);

    let mac_addr = [0x02, 0x5b, 0xbe, 0x00, 0x00, 0x00];
    static STATE: StaticCell<State<8, 8>> = StaticCell::new();
    let state = STATE.init(State::<8, 8>::new());
    let ed = ExclusiveDevice::new(spi, Output::new(cs, Level::High), Delay).unwrap();
    log::info!("before");
    let (device, runner) = embassy_net_wiznet::new::<8, 8, W5500, _, _, _>(
        mac_addr,
        state,
        ed,
        w5500_int,
        w5500_reset,
    )
    .await;
    spawner.spawn(ethernet_task(runner)).unwrap();
    let seed = 0x0123_4567_89ab_cdef;
    static STACK: StaticCell<Stack<Device<'static>>> = StaticCell::new();
    static RESOURCES: StaticCell<StackResources<2>> = StaticCell::new();
    let stack = &*STACK.init(Stack::new(
        device,
        embassy_net::Config::dhcpv4(Default::default()),
        RESOURCES.init(StackResources::<2>::new()),
        seed,
    ));
    spawner.spawn(net_task(stack)).unwrap();

    log::info!("Waiting for DHCP...");
    let cfg = wait_for_config(stack).await;
    // I never reach this line
    let local_addr = cfg.address.address();
    log::info!("IP address: {:?}", local_addr);
    log::info!("after");
    loop {
        log::info!("Hello world!");
        Timer::after(Duration::from_millis(5_000)).await;
    }
}

#[embassy_executor::task]
async fn ethernet_task(
    runner: Runner<
        'static,
        W5500,
        ExclusiveDevice<
            SpiDma<'static, SPI2, Channel0, FullDuplexMode, Async>,
            Output<'static, GpioPin<1>>,
            Delay,
        >,
        Input<'static, GpioPin<3>>,
        Output<'static, GpioPin<2>>,
    >,
) {
    runner.run().await
}

#[embassy_executor::task]
async fn net_task(stack: &'static Stack<Device<'static>>) -> ! {
    log::info!("startNet");
    stack.run().await
}

async fn wait_for_config(stack: &'static Stack<Device<'static>>) -> embassy_net::StaticConfigV4 {
    loop {
        log::info!(
            "Waiting {:?}, {}, {}",
            stack.config_v4(),
            stack.is_link_up(),
            stack.is_config_up()
        );
        if let Some(config) = stack.config_v4() {
            log::info!("got");

            return config.clone();
        }

        Timer::after_millis(500).await;
    }
}
```

my dependencies in the Cargo.toml look like this:

```toml
[dependencies]
embassy-embedded-hal = "0.1.0"
embassy-executor = "0.5.0"
embassy-futures = "0.1.1"
embassy-net = { version = "0.4.0", features = ["dns", "dhcpv4", "medium-ethernet", "tcp", "udp", "proto-ipv4", "proto-ipv6", "dhcpv4-hostname", "medium-ip"] }
embassy-net-wiznet = "0.1.0"
embassy-sync = "0.5.0"
embassy-time = { version = "0.3.1", features = ["generic-queue"] }
embedded-hal-async = "1.0.0"
embedded-hal-bus = { version = "0.2.0", features = ["async"] }
esp-backtrace = { version = "0.12.0", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.18.0", features = ["esp32s3", "async", "embedded-hal-02"] }
esp-hal-embassy = { version = "0.1.0", features = ["esp32s3", "time-timg0"] }
esp-println = { version = "0.9.1", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }
static_cell = { version = "2.1.0", features = ["nightly"] }
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
```

I run the esp32 test example to use wizened w5500 with c code there I got an ip Address. 

Has anybody an idea, what could be the problem here?

Greetings
