### ISSUE TITLE
Is it still recommended to use git link in Cargo.toml?

### ISSUE THREAD

**Issue by BjornTheProgrammer** [embassy-rs/embassy#3331]
[In the book](https://embassy.dev/book/#_cargo_toml_2), the current recommended method of using `embassy` inside your cargo project is to set a patch with its git link and revision. As seen below...

```toml
[dependencies]
embassy-time = { version = "0.2", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

[patch.crates-io]
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "7703f47c1ecac029f603033b7977d9a2becef48c" }
```

This is 9 months old, and I'm wondering if this is still recommended.

If it is still recommended, why is that the case? 

As far as I can tell, the versioning given by cargo ensures much more stability, and clarity of how old your dependencies are. It prevents issues of using the wrong revision. It is easier to set up. Additionally, you might accidentally use a revision of new, unstable, nonpolished code (which has happened to me). Moreover, you cannot push a crate to crates.io with a git link. Finally, it tells you if there are any breaking changes between versions. 

If this is not recommended anymore, should I submit a pull request to update the docs?
