### ISSUE TITLE
Executor alarm missed in nrf time driver

### ISSUE THREAD

**Issue by lulf** [embassy-rs/embassy#3672]
At Akiles we have have seen some cases where a custom critical section that unmasks certain interrupts (see https://github.com/alexmoon/nrf-sdc/blob/main/nrf-mpsl/src/critical_section_impl.rs#L8), causing the nrf time driver alarm to be missed. 

The following code makes the assumption that the time between now() and writing the cc register takes less than 3 ticks: https://github.com/embassy-rs/embassy/blob/main/embassy-nrf/src/time_driver.rs#L212-L252

When using a custom critical section that preempts the time driver in set_alarm, combined with a task that uses a short delay (100 microseconds) wanting to schedule the alarm close to 3 or 4 ticks in the future, it may cause the time driver to miss setting the alarm, causing the executor to not be alarmed of the next task to run.

**Comment by Dirbaio** [comment]
repro: 

do these changes to Cargo.toml

```toml

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm"] }  # remove critical-section-single-core
nrf-mpsl = { git = "https://github.com/alexmoon/nrf-sdc", features = ["critical-section-impl", "nrf52840"] }

[patch.crates-io]
embassy-futures = { path = "../../embassy-futures" }
embassy-sync = { path = "../../embassy-sync" }
embassy-executor = { path = "../../embassy-executor" }
embassy-time = { path = "../../embassy-time" }
embassy-nrf = { path = "../../embassy-nrf" }
embassy-net = { path = "../../embassy-net" }
embassy-usb = { path = "../../embassy-usb" }
embassy-net-esp-hosted = { path = "../../embassy-net-esp-hosted" }
embassy-net-enc28j60 = { path = "../../embassy-net-enc28j60" }
```

then run

```rust
#![no_std]
#![no_main]

use core::mem;

use defmt::{info, unwrap};
use embassy_executor::Spawner;
use embassy_nrf::interrupt;
use embassy_nrf::pac;
use embassy_nrf::peripherals::TIMER0;
use embassy_nrf::{
    interrupt::InterruptExt,
    timer::{Frequency, Timer},
};
use embassy_time::{Duration, Timer as LolTimer};
use {defmt_rtt as _, panic_probe as _};

use nrf_mpsl::{self as _};

static mut CYCLES: u32 = 100;

#[interrupt]
unsafe fn TIMER0() {
    cortex_m::asm::delay(100000); // 3ms

    pac::TIMER0.events_compare(0).write_value(0);

    let timer: Timer<'_, TIMER0> = mem::transmute(());

    CYCLES += 10;
    timer.cc(0).write(CYCLES);
    timer.clear();
    timer.start();
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    let p = embassy_nrf::init(Default::default());

    unsafe { interrupt::TIMER0.enable() }

    let timer = Timer::new(p.TIMER0);
    pac::TIMER0.intenset().write(|w| w.set_compare(0, true));
    timer.set_frequency(Frequency::F16MHz);
    timer.clear();
    timer.cc(0).write(10000);
    timer.cc(0).short_compare_stop();
    timer.start();

    loop {
        info!("boo");
        LolTimer::after(Duration::from_ticks(4)).await;
    }
}
```
