### ISSUE TITLE
time_symbols not present

### ISSUE THREAD

**Issue by JonasFocke01** [embassy-rs/embassy#4118]
Hi,

im in the process of migrating my rp2040 project to embassy. Embassy felt great while tinkering in some examples and writing my own poc.   
Im now facing a linker issue i cannot fix. My usecase feels pretty common, so i would love to write some docs about this for people like me. Or im just blind and does not see it...  
Anyway, my linker complains about the symbols `_embassy_time_now` and `_embassy_time_schedule_wake` not being present. The `embassy-time` crate should do this from my understanding. No? I tried every combination of featureflags i could think of, but no luck.  
Can you spot the error?

My dependencies
```toml
[dependencies]
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
cortex-m = "0.7.2"
fugit = "0.3.5"
embedded-hal = "0.2.5"
smart-leds = "0.3.0"
rw_strip_macros = { path = "src/macros" }
embassy-embedded-hal = "0.3.0"
embassy-sync = "0.6.2"
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-futures = "0.1.1"
embassy-rp = { version = "0.4.0", features = ["rp2040", "critical-section-impl"] }
embassy-time = "0.4.0"
critical-section = "1.2"
```

And here is the error (sorry for the formatting)
<details>
error: linking with `rust-lld` failed: exit status: 1
  |
  = note:  "rust-lld" "-flavor" "gnu" "/tmp/rustcilM5MB/symbols.o" "<1 object files omitted>" "--as-needed" "-Bstatic" "/tmp/rustcilM5MB/{libcortex_m-10fcbb52576aac0d.rlib}.rlib" "<sysroot>/lib/rustlib/thumbv6m-none-eabi/lib/{libcompiler_builtins-*}.rlib" "-Bdynamic" "--eh-frame-hdr" "-z" "noexecstack" "-L" "/home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/build/cortex-m-95a7e83f746eaae0/out" "-L" "/home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/build/cortex-m-rt-9afb7750a8b4e182/out" "-L" "/home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/build/embassy-rp-ad7660851e9e51a6/out" "-L" "/home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/build/rp-pac-2d21cf279e962ef9/out" "-o" "/home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/deps/rw_strip-cb7cd374826dcc4c" "--gc-sections" "-O1" "--nmagic" "-Tlink.x"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: undefined symbol: _embassy_time_now
          >>> referenced by lib.rs:143 (/home/jonas/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-time-driver-0.2.0/src/lib.rs:143)
          >>>               /home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/deps/rw_strip-cb7cd374826dcc4c.smart_leds-aa4f8a4d2af2cf58.smart_leds.309e7de4e52c2670-cgu.0.rcgu.o.rcgu.o:(embassy_executor::raw::TaskStorage$LT$F$GT$::poll::hcd1ff9d362f7d5e8)
          >>> referenced by lib.rs:143 (/home/jonas/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-time-driver-0.2.0/src/lib.rs:143)
          >>>               /home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/deps/rw_strip-cb7cd374826dcc4c.smart_leds-aa4f8a4d2af2cf58.smart_leds.309e7de4e52c2670-cgu.0.rcgu.o.rcgu.o:(embassy_executor::raw::TaskStorage$LT$F$GT$::poll::hcd1ff9d362f7d5e8)

          rust-lld: error: undefined symbol: _embassy_time_schedule_wake
          >>> referenced by lib.rs:148 (/home/jonas/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-time-driver-0.2.0/src/lib.rs:148)
          >>>               /home/jonas/repos/rw_strip/target/thumbv6m-none-eabi/debug/deps/rw_strip-cb7cd374826dcc4c.smart_leds-aa4f8a4d2af2cf58.smart_leds.309e7de4e52c2670-cgu.0.rcgu.o.rcgu.o:(embassy_executor::raw::TaskStorage$LT$F$GT$::poll::hcd1ff9d362f7d5e8)

warning: `rw_strip` (bin "rw_strip") generated 61 warnings
error: could not compile `rw_strip` (bin "rw_strip") due to 1 previous error; 61 warnings emitted
</details>

Do you need to see anything else from me?
