### ISSUE TITLE
Proposal: create nxp-pac for embassy-nxp

### ISSUE THREAD

**Issue by i509VCB** [embassy-rs/embassy#4345]
Progress on `embassy-nxp` is being held back by fragmentation in the `pac` ecosystem. I have tried to get RT1011 and MCXN support going but pac fragmentation is going to make things a real pain. I propose to make a new `nxp-pac` based on chiptool, kind of like `nrf-pac`.

Sure this could be a case of XKCD 927 where more fragmentation comes to exist, but I will discuss some of this below:

This issue also kind of discusses merging embassy-imxrt into embassy-nxp, but only after the pac is up and running and things have been migrated.

Using off the shelf crates for pacs, there are a few groups of crates, of which each are generated differently. This is a non-exhaustive list:
- LPC
  - [lpc55-pac](https://github.com/lpc55/lpc55-pac) (used by embassy-nxp currently) - svd2rust
- i.MXRT
  - [imxrt-ral](https://github.com/imxrt-rs/imxrt-ral) - chiptool fork which is radically different to use, does not cover RT500, 600, 700
  - [mimxrt685s-pac](https://github.com/OpenDevicePartnership/mimxrt685s-pac) - used in embassy-imxrt, svd2rust
  - [mimxrt633s-pac](https://github.com/OpenDevicePartnership/mimxrt633s-pac) - used in embassy-imxrt, svd2rust
  - [imxrt-pacs](https://github.com/korbin/imxrt-pacs) - RT1011 only, also has some code that embassy-nxp can use.
- MCX
  - [mcx-pac](https://github.com/mcx-rs/mcx-pac) - chiptool, but with `Instance` types. 
- Kinetis
  - [k64](https://github.com/stefanhoelzl/k64), [k66](https://github.com/stv0g/k66) - svd2rust, likely abadoned as these are 6+ years old
  - [ke06z4-pac](https://crates.io/crates/ke06z4-pac) - svd2rust

## Should we bother?

It would be easy to create `embassy-mcx`, `embassy-lpc`, `embassy-imxrt` crates, but PACs are not internally consistent within the same families (with imxrt).

However there is a lot of IP shared between parts. I quick skim through some reference manuals to show where there are matches and no matches, so specific things may be wrong. This is of course a non exhaustive list:

- USB HS PHY
  - Shared by MCXNx4x, RT6xx, RT101x, K26, LPC55
- USB HS
  - Shared by MCXNx4x, RT101x, K26
- USB FS
  - Shared by MCXNx4x, K26
- FlexIO
  - Shared with MCXNx4x, RT101x
- FlexSPI
  - Shared with RT6xx, RT101x, MCXNx4x (same base, but extended)
- LPUART
  - RT101x, K26
- Flexcomm
  - LPC55, RT6xx
- OSTIMER
  - MCXNx4x, RT6xx, LPC55
- PowerQuad DSP
  - MCXNx4x, RT6xx, LPC55
- SDHC
  - MCXNx4x, K26, RT6xx
- I3C
  - MCXNx4x, RT6xx
- FlexCAN
  - MCXNx4x, K26

And some examples of complete no-matches:
- GPIO (completely different on each family I skimmed)
- Flexcomm: LP for MCX, non-LP for RT-6xx, not present on RT1xxx
- "pad configuration": IOMUXc for RT1xxx, IOCON for RT6xx, different IOCON for LPC55
- DMA

In some cases, we would be writing a driver for the same IP 4 times (USB HS PHY) and 2-3 times often. Doing this in a fashion that doesn't involve big `#[cfg(...)]` blocks that only differ in the style of pac being used will make things hard to maintain. This is why I would propose an nxp-pac.

## Data sources

We have the following data sources we can use for this:
- SVD files: https://github.com/nxp-mcuxpresso/mcux-soc-svd
- All the mcux-devices-* repositories. It also describes "peripheral versions", so for MCX at least we could minimize the amount of duplicate code around. Although I would still opt to use SVDs to prevent little inconsistencies from being a problem (especially so with RT). There are also linker scripts:
  - https://github.com/nxp-mcuxpresso/mcux-devices-wireless
  - https://github.com/nxp-mcuxpresso/mcux-devices-rt
  - https://github.com/nxp-mcuxpresso/mcux-devices-mcx
  - https://github.com/nxp-mcuxpresso/mcux-devices-lpc
  - https://github.com/nxp-mcuxpresso/mcux-devices-kinetis

## PAC specifics

Things will be generated from svds which then get a pass through chiptool to make things consistent/usable.

Since pad setup and gpio muxing will differ significantly by device, I would suggest doing what is done in nrf-pac by defining each chip in the `chips` folder and then using the `impl_foo!` macros. This however scales a little less nicely because of packages (although nrf-pac kind of ignores packages in the first place). And then kind of like stm32-metapac maybe a type like `AfType` so that the UART driver for example doesn't need to care about whether the IOMUXC or IOCON is being used?

I (unfortunately) would probably end up being the maintainer for this lol (alongside the mspm0 stuff I've already started)

I would appreciate some comments from @george-cosma (lpc55), @felipebalbi (rt6xx) and @korbin, but am also open to discussion around making this practical or alternatives.

**Comment by felipebalbi** [comment]
I think it's a very valid goal, assuming it's doable. The problem I see is that NXP SVDs are not the best, honestly. Look at the amount of patches on both [RT633 ](https://github.com/OpenDevicePartnership/mimxrt633s-pac/tree/main/patch)and [RT685](https://github.com/OpenDevicePartnership/mimxrt685s-pac/tree/main/patch). I don't even think those patches cover all issues. That being said, some of the patches are more for `svd2rust` to generate the proper bit accessors for W1C, W1S, W0C, and W0S bits.

Sadly, we already have `embassy-imxrt` and `embassy-nxp` in the main branch. Combining them is doable, but might cause issues to downstream users. At least for `embassy-imxrt`, downstream users are still pulling from the original [fork ](https://github.com/OpenDevicePartnership/embassy-imxrt). In some situations, maybe a clean slate implementation would not be a bad idea.

(partially) Related, wassasin has been working through `probe-rs` issues with RT600, if that's sorted out, we can probably figure out a way to get RT685 EVK in @Dirbaio's test runners, I mean, assuming it's okay; we'll figure out if/how/when to get boards :)

**Comment by eva-cosma** [comment]
Hello! While I cannot comment on what possible issues and complications might come about due to a mega-pac, having only experience with LPC55 products, I am still in favour of this. If it works out, amazing, if it doesn't then at least we tried and eliminated one way of doing things. The only major risk that could pose a problem is having slight (undocumented) differences within an IP across  different chips, but I don't think we will find this out without at least trying.

W/R/T the `embassy-imxrt` situation, I think the original proposal is sane - combining only after mega-pac completion. There is nothing we can do if people don't want to switch -- it's their code, their business. If they want updates, they have to switch. We should at least try to aim to make that switch as seamless as possible or at least well-documented.

I'll try to help out with this project, but I'm also mentoring some interns and I might be able to bring them on-board for this, for extra firepower.

**Comment by korbin** [comment]
From my experience, the SVDs weren't "terrible" for the IMXRT10xx, but there were enough inconsistencies to require patches for sure. I ended up forking `chiptool` to add a few transforms to help clean these up (but maintained the same interface.)

I am for merging everything - but I don't have much of a dog in this fight (I can port and work on drivers once the PAC stuff is settled.)

I do hope that the `chiptool` accessor methods approach is maintained (as with all existing Embassy PACs/HALs): I can't use something that requires autocomplete/`rustfmt`-destroying macros at every register access call site.

**Comment by felipebalbi** [comment]
Based on the answers here, seems like there's interest, but none of us can dedicate a lot of time to the PAC. @i509VCB, how would you like to start?

FYI, all NXP SVDs are available [here](https://github.com/nxp-mcuxpresso/mcux-soc-svd). I suppose an easy way to start would be choose one part and generate a PAC with `chiptool`? That would at least give us a starting point.

**Comment by i509VCB** [comment]
I have started a pac crate based off the SVDs. I will try to publish it in a bit.

So far I've gotten RT1011 and RT1062 generating and wrote some patches to clean up the GPIO and IOMUXC blocks (the HAL is going to know the alt mode values anyways). GPIO is going to differ on each part anyways. 

I would then get MCXNx4x generating to a GPIO driver and then try to get the gpio drivers into embassy-nxp. RT600 differs on GPIO for all the parts iirc? 

I don't have any LPC55 boards but I will try to get that on to PAC as well and port the current gpio driver. The pint driver I don't fully understand and is probably going to be just more device specific code.

**Comment by SpinFast** [comment]
I didn't have any problems with autocomplete and the imxrt-ral style macros. Autocomplete on finding the module, register, and field worked fine.

The blurb here https://github.com/imxrt-rs/imxrt-ral/?tab=readme-ov-file#why-not-use-svd2rust-to-generate-a-crate-for-register-access suggests the svd2rust route isn't great, has anyone tested this out on imxrt1060 or imxrt1176? Has anyone tried using chiptool/svd2rust on one of the larger parts? If it takes a lot of time to build that's a con. Build time matters.

I helped write the SAI driver which is now in imxrt-hal and didn't mind the macros much. The closures are nicer I guess, but the macros are fairly obvious. I had tried sending a patch to chiptool to support external devices for the wm8960 codec on the imxrt evk boards but this was never reviewed sadly. If chiptool maintainers/reviewers were open to accepting patches for merging svds and patching svds like imxrt-ral does while still outputting svd2rust output I might consider putting up the work for this. But having seen my last patch go without review I'm not willing to do anything unless I hear this would be accepted. So @Dirbaio I guess would need to chime in on this?

Going that route though would mean working PACs presumably for 101x to 118x instantly. And the pad/iomux work already done, along with the drivers (ported to the PACs) could be reused perhaps saving a lot of time.

**Comment by diondokter** [comment]
Yeah, so my device-driver crate solves a similar issue, but is likely not a good pick for a PAC. It can work, but it makes some choices which means it wouldn't be nice to work with as a PAC.

With regard to the other options, I personally dislike the way RAL does things. Seems like a step back.
We now have two metapack families using chiptool. One for STM and one for MSPM0. I think it makes sense to go in that direction too

**Comment by SpinFast** [comment]
> Yeah, so my device-driver crate solves a similar issue, but is likely not a good pick for a PAC. It can work, but it makes some choices which means it wouldn't be nice to work with as a PAC.
> 
> With regard to the other options, I personally dislike the way RAL does things. Seems like a step back. We now have two metapack families using chiptool. One for STM and one for MSPM0. I think it makes sense to go in that direction too

I was more talking about that because I'm happy to port the patches from raltool to chiptool and push them upstream to support the same kind of flows but with chiptool output, but only if its going to get reviewed.

**Comment by i509VCB** [comment]
Even if I did want to use the imxrt-ral output with a regular chiptool output, I would probably need to do some significant type deduplication and svd cleanup to match other nxp parts. For example the SVDs have individual types for each IOMUXC MUX selection. This makes sense with the RAL output or in C, but results in loads of extra matching in how embassy does things.

I do know of the imxrt-iomuxc crate which makes that interface generic, but that works around the problem with raw pointer access.

An example is the IOMUXc patches I wrote for the imxrt part of the pac to just remove duplicate types and turn the mux values for a pad into an integer (because it will differ for each chip):
```yaml
# Merge and clean up common enums
transforms:
  #! Resize all mux mode enums to maximum size (4 bits).
  #!
  #! RT1011 has 3 bits usable, with a single 1 bit entry.
  - !ResizeEnums
    enum: (iomuxc|iomuxc_snvs)::vals::SwMuxCtlPad(.*)?MuxMode
    bit_size: 4

  - !DeleteEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwMuxCtlPad(.*)?MuxMode
    bit_size: 4

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwMuxCtlPad(.*)?Sion
    to: $1::vals::Sion
    check: Layout

  - !MergeFieldsets
    from: (iomuxc|iomuxc_snvs)::regs::SwMuxCtlPad(.*)?
    to: $1::regs::MuxCtl

  #! A large number of enums
  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Speed
    to: $1::vals::Speed
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Pus
    to: $1::vals::Pus
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Dse
    to: $1::vals::Dse
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Sre
    to: $1::vals::Sre
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Hys
    to: $1::vals::Hys
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Ode
    to: $1::vals::Ode
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Pke
    to: $1::vals::Pke
    check: Layout

  - !MergeEnums
    from: (iomuxc|iomuxc_snvs)::vals::SwPadCtlPad(.*)?\d+Pue
    to: $1::vals::Pue
    check: Layout

  - !MergeFieldsets
    from: iomuxc::regs::SwPadCtlPad(.*)?
    to: iomuxc::regs::Ctl
```

These one patch results in the changes of output code:
|Part      | kLOC before | kLOC after |
|-----------|--------------------|-----------------|
|RT1011| 190k | 168k |
|RT1062| 493k | 420k |

Plus with how embassy works, we would collect the IOMUXC MUX data in another way and provide it via the `WhateverPin` traits we make.
