### ISSUE TITLE
embassy-stm32 with feature low-power does not compile on STM32WB55

### ISSUE THREAD

**Issue by diego-gpio** [embassy-rs/embassy#4352]
Adding feature flag to embassy-stm32 on `Cargo.toml`

These are the relevant lines on my 
```toml
[dependencies]
embassy-stm32 = { version = "0.2.0", features = ["defmt", "stm32wb55rg", "exti", "time-driver-any", "time", "unstable-pac", "low-power"] }
embassy-sync = { version = "0.7.0", features = ["defmt"] }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heapless = { version = "0.8", default-features = false }
static_cell = "2"
embassy-futures = { version = "0.1.1", features = ["defmt"] }
```
And the error output:

```rust
   Compiling embassy-stm32 v0.2.0
error[E0046]: not all trait items implemented, missing: `EXTI_WAKEUP_LINE`, `WakeupInterrupt`
   --> /Users/dbarranco/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-stm32-0.2.0/src/rtc/v2.rs:128:1
    |
128 | impl SealedInstance for crate::peripherals::RTC {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `EXTI_WAKEUP_LINE`, `WakeupInterrupt` in implementation
    |
   ::: /Users/dbarranco/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-stm32-0.2.0/src/rtc/mod.rs:289:5
    |
289 |     const EXTI_WAKEUP_LINE: usize;
    |     ----------------------------- `EXTI_WAKEUP_LINE` from trait
...
292 |     type WakeupInterrupt: crate::interrupt::typelevel::Interrupt;
    |     ------------------------------------------------------------ `WakeupInterrupt` from trait

error[E0599]: no method named `imr` found for struct `Exti` in the current scope
   --> /Users/dbarranco/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-stm32-0.2.0/src/rtc/low_power.rs:234:18
    |
234 |             EXTI.imr(0).modify(|w| w.set_line(RTC::EXTI_WAKEUP_LINE, true));
    |                  ^^^ method not found in `Exti`

Some errors have detailed explanations: E0046, E0599.
For more information about an error, try `rustc --explain E0046`.
``` 

I tried following the low power configuration shown in the embassy documentation https://docs.embassy.dev/embassy-stm32/git/stm32f410rb/low_power/index.html but it is not clear if I'm missing something on the .toml file.
