### ISSUE TITLE
stm32: SPI DMA macros do not support peripherals where one channel allows for multiple requests.

### ISSUE THREAD

**Issue by matoushybl** [embassy-rs/embassy#443]
In SPI5 on STM32F767ZI, the dma channels are defined as follows:
```yaml
dma_channels:
        RX:
        - channel: DMA2_CH3
          request: 2
        - channel: DMA2_CH5
          request: 7
        - channel: DMA2_CH5
          request: 9
```
Which causes problem as the current DMA implementation allows for only one request per channel per peripheral.
https://github.com/embassy-rs/embassy/blob/2b4e2bcbaeed7702fd78dafcaa7bd30570f2c746/embassy-stm32/src/spi/mod.rs#L154-L162

Which results in compilation error:
```
error[E0119]: conflicting implementations of trait `spi::sealed::RxDmaChannel<generated::peripherals::SPI5>` for type `generated::peripherals::DMA2_CH5`
   --> /Users/matous/Development/Rust/Embedded/Libs/embassy/embassy-stm32/src/spi/mod.rs:155:9
    |
155 |           impl sealed::$signal<peripherals::$inst> for peripherals::$channel {
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |           |
    |           first implementation here
    |           conflicting implementation for `generated::peripherals::DMA2_CH5`
...
165 | / crate::pac::peripheral_dma_channels! {
166 | |     ($peri:ident, spi, $kind:ident, RX, $channel:tt, $request:expr) => {
167 | |         impl_dma!($peri, $channel, RxDmaChannel, $request);
168 | |     };
...   |
171 | |     };
172 | | }
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `impl_dma` (in Nightly builds, run with -Z macro-backtrace for more info)
```
